import { Token, Trend } from "./token.types";

const trends: Trend[] = ["up", "down", "neutral", "alert"];
const randomTrend = (): Trend => trends[Math.floor(Math.random() * trends.length)];
const randomPrice = () => +(Math.random() * 4 - 2).toFixed(2);

export const TOKENS: Token[] = [
  // 1–3: New Pairs
  {
    id: "1",
    name: "Candy Cane Coin",
    description: "Sweet new token",
    imageUrl: "https://www.cryptologos.cc/logos/candy-candy-logo.png",
    walletAddress: "CaNy...0001",
    timeAgo: "30s",
    replies: 2,
    upvotes: 12,
    downvotes: 1,
    watchlistCount: 5,
    views: 22,
    marketCap: "$5.2K",
    volume: "$410",
    floor: "0.0012",
    txCount: 8,
    holderPercent: "4%",
    devPercent: "2%",
    devTime: "3mo",
    targetPercent: "10%",
    lockPercent: "1%",
    giftPercent: "0%",
    showVerified: true,
    priceChange: randomPrice(),
    priceTrend: randomTrend(),
    borderTrend: randomTrend(),
    badgeTrend: randomTrend(),
    category: "New Pairs",
  },
  {
    id: "2",
    name: "Snowflake Token",
    description: "Cool fun vibes",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Bitcoin.svg/1200px-Bitcoin.svg.png",
    walletAddress: "SnFl...0002",
    timeAgo: "45s",
    replies: 1,
    upvotes: 8,
    downvotes: 0,
    watchlistCount: 3,
    views: 18,
    marketCap: "$7.1K",
    volume: "$890",
    floor: "0.0034",
    txCount: 12,
    holderPercent: "6%",
    devPercent: "5%",
    devTime: "1mo",
    targetPercent: "5%",
    lockPercent: "3%",
    giftPercent: "1%",
    showVerified: false,
    priceChange: randomPrice(),
    priceTrend: randomTrend(),
    borderTrend: randomTrend(),
    badgeTrend: randomTrend(),
    category: "New Pairs",
  },
  {
    id: "3",
    name: "Minty Fresh",
    description: "Fresh like mint",
    imageUrl: "https://cryptologos.cc/logos/ethereum-eth-logo.png",
    walletAddress: "MiNt...0003",
    timeAgo: "1m",
    replies: 3,
    upvotes: 9,
    downvotes: 2,
    watchlistCount: 4,
    views: 20,
    marketCap: "$3.9K",
    volume: "$210",
    floor: "0.0021",
    txCount: 5,
    holderPercent: "2%",
    devPercent: "1%",
    devTime: "6mo",
    targetPercent: "8%",
    lockPercent: "2%",
    giftPercent: "0%",
    showVerified: true,
    priceChange: randomPrice(),
    priceTrend: randomTrend(),
    borderTrend: randomTrend(),
    badgeTrend: randomTrend(),
    category: "New Pairs",
  },
  
  

  // 6–10: Final Stretch (5 tokens)
  {
    id: "6",
    name: "Blizzard Boost",
    description: "Final rally ahead",
    imageUrl: "https://cryptologos.cc/logos/polkadot-new-dot-logo.png",
    walletAddress: "BlzB...0006",
    timeAgo: "2m",
    replies: 4,
    upvotes: 20,
    downvotes: 3,
    watchlistCount: 8,
    views: 35,
    marketCap: "$8.8K",
    volume: "$1.2K",
    floor: "0.0048",
    txCount: 14,
    holderPercent: "7%",
    devPercent: "3%",
    devTime: "4mo",
    targetPercent: "15%",
    lockPercent: "2%",
    giftPercent: "1%",
    showVerified: true,
    priceChange: randomPrice(),
    priceTrend: randomTrend(),
    borderTrend: randomTrend(),
    badgeTrend: randomTrend(),
    category: "Final Stretch",
  },
  
  
  {
    id: "10",
    name: "Polar Token",
    description: "Arctic strength",
    imageUrl: "https://cryptologos.cc/logos/litecoin-ltc-logo.png",
    walletAddress: "PoTo...0010",
    timeAgo: "2m",
    replies: 1,
    upvotes: 14,
    downvotes: 1,
    watchlistCount: 6,
    views: 32,
    marketCap: "$11.7K",
    volume: "$1.8K",
    floor: "0.0063",
    txCount: 17,
    holderPercent: "9%",
    devPercent: "4%",
    devTime: "3mo",
    targetPercent: "14%",
    lockPercent: "3%",
    giftPercent: "1%",
    showVerified: false,
    priceChange: randomPrice(),
    priceTrend: randomTrend(),
    borderTrend: randomTrend(),
    badgeTrend: randomTrend(),
    category: "Final Stretch",
  },


  {
    id: "11",
    name: "Icicle Icon",
    description: "Migrated and cooler",
    imageUrl: "https://cryptologos.cc/logos/dogecoin-doge-logo.png",
    walletAddress: "IcIc...0011",
    timeAgo: "5m",
    replies: 2,
    upvotes: 5,
    downvotes: 1,
    watchlistCount: 2,
    views: 14,
    marketCap: "$4.2K",
    volume: "$510",
    floor: "0.0019",
    txCount: 7,
    holderPercent: "3%",
    devPercent: "2%",
    devTime: "7mo",
    targetPercent: "6%",
    lockPercent: "3%",
    giftPercent: "1%",
    showVerified: false,
    priceChange: randomPrice(),
    priceTrend: randomTrend(),
    borderTrend: randomTrend(),
    badgeTrend: randomTrend(),
    category: "Migrated",
  },
  {
    id: "12",
    name: "Aurora Token",
    description: "Migrated bright star",
    imageUrl: "https://cryptologos.cc/logos/binance-coin-bnb-logo.png",
    walletAddress: "AuRo...0012",
    timeAgo: "4m",
    replies: 1,
    upvotes: 7,
    downvotes: 0,
    watchlistCount: 3,
    views: 19,
    marketCap: "$6.5K",
    volume: "$790",
    floor: "0.0027",
    txCount: 9,
    holderPercent: "4%",
    devPercent: "1%",
    devTime: "8mo",
    targetPercent: "9%",
    lockPercent: "5%",
    giftPercent: "0%",
    showVerified: true,
    priceChange: randomPrice(),
    priceTrend: randomTrend(),
    borderTrend: randomTrend(),
    badgeTrend: randomTrend(),
    category: "Migrated",
  },
  
 
];