import { Token, Trend } from "./token.types";

const trends: Trend[] = ["up", "down", "neutral", "alert"];
const randomTrend = (): Trend => trends[Math.floor(Math.random() * trends.length)];
const randomPrice = () => +(Math.random() * 4 - 2).toFixed(2);

export const TOKENS: Token[] = [
  // 1–5: New Pairs
  {
    id: "1",
    name: "Candy Cane Coin",
    description: "Sweet new token",
    imageUrl: "https://media.giphy.com/media/3oEjI6SIIHBdRxXI40/giphy.gif",
    walletAddress: "CaNy...0001",
    timeAgo: "30s",
    replies: 2,
    upvotes: 12,
    downvotes: 1,
    watchlistCount: 5,
    views: 22,
    marketCap: "$5.2K",
    volume: "$410",
    floor: "0.0012",
    txCount: 8,
    holderPercent: "4%",
    devPercent: "2%",
    devTime: "3mo",
    targetPercent: "10%",
    lockPercent: "1%",
    giftPercent: "0%",
    showVerified: true,
    priceChange: randomPrice(),
    priceTrend: randomTrend(),
    borderTrend: randomTrend(),
    badgeTrend: randomTrend(),
    category: "New Pairs",
  },
  {
    id: "2",
    name: "Snowflake Token",
    description: "Cool fun vibes",
    imageUrl: "https://media.giphy.com/media/8ZC33CWjaXCRq/giphy.gif",
    walletAddress: "SnFl...0002",
    timeAgo: "45s",
    replies: 1,
    upvotes: 8,
    downvotes: 0,
    watchlistCount: 3,
    views: 18,
    marketCap: "$7.1K",
    volume: "$890",
    floor: "0.0034",
    txCount: 12,
    holderPercent: "6%",
    devPercent: "5%",
    devTime: "1mo",
    targetPercent: "5%",
    lockPercent: "3%",
    giftPercent: "1%",
    showVerified: false,
    priceChange: randomPrice(),
    priceTrend: randomTrend(),
    borderTrend: randomTrend(),
    badgeTrend: randomTrend(),
    category: "New Pairs",
  },
  {
    id: "3",
    name: "Minty Fresh",
    description: "Fresh like mint",
    imageUrl: "https://media.giphy.com/media/l0MYK3o6t1qi4EJq4/giphy.gif",
    walletAddress: "MiNt...0003",
    timeAgo: "1m",
    replies: 3,
    upvotes: 9,
    downvotes: 2,
    watchlistCount: 4,
    views: 20,
    marketCap: "$3.9K",
    volume: "$210",
    floor: "0.0021",
    txCount: 5,
    holderPercent: "2%",
    devPercent: "1%",
    devTime: "6mo",
    targetPercent: "8%",
    lockPercent: "2%",
    giftPercent: "0%",
    showVerified: true,
    priceChange: randomPrice(),
    priceTrend: randomTrend(),
    borderTrend: randomTrend(),
    badgeTrend: randomTrend(),
    category: "New Pairs",
  },
  
  

  // 6–10: Final Stretch
  {
    id: "6",
    name: "Blizzard Boost",
    description: "Final rally ahead",
    imageUrl: "https://media.giphy.com/media/l0ExncehJzexFpRHq/giphy.gif",
    walletAddress: "BlzB...0006",
    timeAgo: "2m",
    replies: 4,
    upvotes: 20,
    downvotes: 3,
    watchlistCount: 8,
    views: 35,
    marketCap: "$8.8K",
    volume: "$1.2K",
    floor: "0.0048",
    txCount: 14,
    holderPercent: "7%",
    devPercent: "3%",
    devTime: "4mo",
    targetPercent: "15%",
    lockPercent: "2%",
    giftPercent: "1%",
    showVerified: true,
    priceChange: randomPrice(),
    priceTrend: randomTrend(),
    borderTrend: randomTrend(),
    badgeTrend: randomTrend(),
    category: "Final Stretch",
  },
  {
    id: "7",
    name: "Frost Flow",
    description: "Chilly but strong",
    imageUrl: "https://media.giphy.com/media/xUPGcEliCc7bETyfO8/giphy.gif",
    walletAddress: "FrSt...0007",
    timeAgo: "3m",
    replies: 0,
    upvotes: 15,
    downvotes: 2,
    watchlistCount: 6,
    views: 28,
    marketCap: "$9.3K",
    volume: "$980",
    floor: "0.0033",
    txCount: 11,
    holderPercent: "5%",
    devPercent: "3%",
    devTime: "2mo",
    targetPercent: "10%",
    lockPercent: "4%",
    giftPercent: "2%",
    showVerified: false,
    priceChange: randomPrice(),
    priceTrend: randomTrend(),
    borderTrend: randomTrend(),
    badgeTrend: randomTrend(),
    category: "Final Stretch",
  },
  {
    id: "8",
    name: "Iceberg Token",
    description: "Big and cool",
    imageUrl: "https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif",
    walletAddress: "IcBg...0008",
    timeAgo: "1m",
    replies: 2,
    upvotes: 12,
    downvotes: 1,
    watchlistCount: 5,
    views: 25,
    marketCap: "$7.4K",
    volume: "$650",
    floor: "0.0029",
    txCount: 10,
    holderPercent: "6%",
    devPercent: "2%",
    devTime: "3mo",
    targetPercent: "12%",
    lockPercent: "2%",
    giftPercent: "0%",
    showVerified: true,
    priceChange: randomPrice(),
    priceTrend: randomTrend(),
    borderTrend: randomTrend(),
    badgeTrend: randomTrend(),
    category: "Final Stretch",
  },

  // 11–15: Migrated
  {
    id: "9",
    name: "Icicle Icon",
    description: "Migrated and cooler",
    imageUrl: "https://media.giphy.com/media/4Zo41lhzKt6iZ8xff9/giphy.gif",
    walletAddress: "IcIc...0009",
    timeAgo: "5m",
    replies: 2,
    upvotes: 5,
    downvotes: 1,
    watchlistCount: 2,
    views: 14,
    marketCap: "$4.2K",
    volume: "$510",
    floor: "0.0019",
    txCount: 7,
    holderPercent: "3%",
    devPercent: "2%",
    devTime: "7mo",
    targetPercent: "6%",
    lockPercent: "3%",
    giftPercent: "1%",
    showVerified: false,
    priceChange: randomPrice(),
    priceTrend: randomTrend(),
    borderTrend: randomTrend(),
    badgeTrend: randomTrend(),
    category: "Migrated",
  },
  {
    id: "10",
    name: "Aurora Token",
    description: "Migrated bright star",
    imageUrl: "https://media.giphy.com/media/26BRzozg4TCBXv6QU/giphy.gif",
    walletAddress: "AuRo...0010",
    timeAgo: "4m",
    replies: 1,
    upvotes: 7,
    downvotes: 0,
    watchlistCount: 3,
    views: 19,
    marketCap: "$6.5K",
    volume: "$790",
    floor: "0.0027",
    txCount: 9,
    holderPercent: "4%",
    devPercent: "1%",
    devTime: "8mo",
    targetPercent: "9%",
    lockPercent: "5%",
    giftPercent: "0%",
    showVerified: true,
    priceChange: randomPrice(),
    priceTrend: randomTrend(),
    borderTrend: randomTrend(),
    badgeTrend: randomTrend(),
    category: "Migrated",
  },
  {
    id: "11",
    name: "Northern Lights",
    description: "Migrated aurora vibes",
    imageUrl: "https://media.giphy.com/media/3oKIPwoeGErMmaI43C/giphy.gif",
    walletAddress: "NoLi...0011",
    timeAgo: "6m",
    replies: 0,
    upvotes: 4,
    downvotes: 0,
    watchlistCount: 1,
    views: 12,
    marketCap: "$3.8K",
    volume: "$420",
    floor: "0.0015",
    txCount: 6,
    holderPercent: "2%",
    devPercent: "1%",
    devTime: "5mo",
    targetPercent: "4%",
    lockPercent: "1%",
    giftPercent: "0%",
    showVerified: false,
    priceChange: randomPrice(),
    priceTrend: randomTrend(),
    borderTrend: randomTrend(),
    badgeTrend: randomTrend(),
    category: "Migrated",
  },
];
